app = "cpz-atlas"
primary_region = "iad"

[http_service]
  internal_port = 3000
  force_https = true

[env]
  NEXT_PUBLIC_MAPBOX_TOKEN = "your-actual-mapbox-token"
  NEXT_PUBLIC_API_BASE_URL = "https://cpz-atlas-backend.fly.dev"
